#!/usr/bin/env python3
"""
svg_validator.py
=====================================

Purpose:
    Static validation gate for SVG blueprints generated by the
    garden-structure-designer pipeline. Checks XML well-formedness,
    presence of required dimensional labels, and structural topology counts.

    Implements Dual-Channel QA Axis 1 (Static XML) from the validation-agent
    protocol. Must be run on every generated SVG before proceeding to the
    next pipeline stage.

Layer: Investigate

Usage:
    python3 scripts/svg_validator.py <svg_file> <path-to-structural-model.json>

Exit codes:
    0 — All checks passed.
    1 — One or more checks failed (details printed to stdout).
"""
from __future__ import annotations

import json
import os
import re
import sys
import xml.etree.ElementTree as ET
from typing import Optional


# ---------------------------------------------------------------------------
# Validation logic
# ---------------------------------------------------------------------------


def _load_geometry_calcs(model_path: str) -> Optional[dict]:
    """
    Load geometry-calculations.json if it exists alongside structural-model.json.

    Args:
        model_path: Path to structural-model.json.

    Returns:
        Parsed geometry-calculations dict, or None if file is absent.
    """
    calc_path = os.path.join(os.path.dirname(model_path), "geometry-calculations.json")
    if os.path.exists(calc_path):
        with open(calc_path) as f:
            return json.load(f)
    return None


def _check_xml_validity(svg_path: str, raw: str) -> list[str]:
    """
    Validate SVG XML well-formedness.

    Checks:
    - Parseable by ElementTree (no broken tags, unescaped characters, etc.).
    - No double-hyphen (--) inside XML comment bodies (illegal per XML 1.0).

    Args:
        svg_path: File path for error messages.
        raw: Raw SVG file contents as string.

    Returns:
        List of error message strings (empty if all pass).
    """
    errors: list[str] = []

    try:
        ET.fromstring(raw)
    except ET.ParseError as exc:
        errors.append(f"XML_INVALID: {exc}")
        return errors  # Cannot safely proceed with further checks

    for match in re.finditer(r"<!--(.*?)-->", raw, re.DOTALL):
        body = match.group(1)
        if "--" in body:
            errors.append(
                "XML_COMMENT: Illegal double-hyphen (--) found inside comment body. "
                "XML 1.0 §2.5 forbids this."
            )
    return errors


def _check_dimension_labels(
    raw: str,
    model: dict,
    calcs: Optional[dict],
) -> list[str]:
    """
    Verify that critical dimension labels are present in the SVG text content.

    Args:
        raw: Raw SVG file contents.
        model: Parsed structural-model.json.
        calcs: Parsed geometry-calculations.json, or None.

    Returns:
        List of error strings for any missing labels.
    """
    errors: list[str] = []

    # --- Roof pitch label ---
    members = model.get("members") or model.get("structuralElements", {})
    roof = members.get("roofStructure") or model.get("roofStructure", {})
    pitch = roof.get("pitch", "4:12")
    pitch_prefix = pitch.split(":")[0]  # e.g. "4" for "4:12"
    if pitch_prefix + ":12" not in raw:
        errors.append(
            f"MISSING_PITCH_LABEL: '{pitch}' pitch label not found in SVG text nodes."
        )

    # --- Compound angle labels (only when geometry-calculations.json is available) ---
    if calcs:
        cuts = calcs.get("compound_cut", {})
        miter = str(round(cuts.get("miter_deg", 0), 1))
        if miter not in raw:
            errors.append(
                f"MISSING_MITER_ANGLE: miter angle {miter}° not found in SVG. "
                f"Expected from geometry-calculations.json."
            )

    return errors


def _check_topology_count(raw: str, model: dict) -> list[str]:
    """
    Count structural post elements in the SVG against the JSON quantity.

    Uses the canonical cedar fill colour (#c8a96e) as a proxy for post elements.
    Sheets that are not topology views should include <!-- TOPOLOGY_SKIP -->
    in their XML to suppress this check.

    Args:
        raw: Raw SVG file contents.
        model: Parsed structural-model.json.

    Returns:
        List of error strings if count mismatches (empty if skip or pass).
    """
    if "TOPOLOGY_SKIP" in raw:
        return []

    members = model.get("members") or model.get("structuralElements", {})
    posts = members.get("posts", {})
    expected_qty: int = posts.get("quantity", 6)

    # Count elements with the canonical post cedar fill colour
    found = len(re.findall(r'fill="#c8a96e"', raw))
    if found > 0 and found < expected_qty:
        return [
            f"TOPOLOGY_COUNT: Expected {expected_qty} post elements "
            f"(fill=#c8a96e), found {found}. "
            f"Add <!-- TOPOLOGY_SKIP --> if this is a detail sheet."
        ]
    return []


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def validate(svg_path: str, model_path: str) -> list[str]:
    """
    Run all validation checks on a single SVG against structural-model.json.

    Args:
        svg_path: Path to the SVG file to validate.
        model_path: Path to context/staging/structural-model.json.

    Returns:
        List of error strings. Empty list means PASS.
    """
    with open(svg_path) as f:
        raw = f.read()

    with open(model_path) as f:
        model = json.load(f)

    calcs = _load_geometry_calcs(model_path)

    errors: list[str] = []
    errors.extend(_check_xml_validity(svg_path, raw))

    # Abort further checks if XML is broken — other checks will give false results
    if errors:
        return errors

    errors.extend(_check_dimension_labels(raw, model, calcs))
    errors.extend(_check_topology_count(raw, model))
    return errors


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """Parse CLI arguments and run validation, printing results to stdout."""
    if len(sys.argv) < 3:
        print(
            "Usage: python3 scripts/svg_validator.py "
            "<svg_file> <path-to-structural-model.json>",
            file=sys.stderr,
        )
        sys.exit(1)

    svg_path, model_path = sys.argv[1], sys.argv[2]
    errors = validate(svg_path, model_path)

    if errors:
        print("VALIDATION FAILED:")
        for err in errors:
            print(f"  ✗ {err}")
        sys.exit(1)
    else:
        print(f"VALIDATION PASSED ✓  ({svg_path})")
        sys.exit(0)


if __name__ == "__main__":
    main()
