#!/usr/bin/env python3
"""
visual_svg_smoke_test.py (CLI)
=====================================

Purpose:
    Performs visual verification and topology auditing of SVGs generated by
    the timber-frame-cad engine. Utilizes headless Chromium via Playwright
    to capture screenshots and runs computer vision algorithms (Canny edge,
    Hough line transforms) via OpenCV to validate structural features.

Layer: QA Validation

Usage Examples:
    python3 visual_svg_smoke_test.py \
      --structure context/staging/structural-model.json \
      --svg-dir outputs/ \
      --out-dir outputs/visual-smoke/ \
      --report-json context/staging/visual-smoke-report.json \
      --report-md outputs/visual-smoke-report.md

Supported Object Types:
    SVG, JSON, PNG, Markdown

CLI Arguments:
    --structure: Path to locked staging structure JSON model.
    --svg-dir: Path to folder containing the 8 output SVGs.
    --out-dir: Output directory to save the raster PNGs.
    --report-json: Output JSON report file.
    --report-md: Output Markdown report file.
    --baseline-dir: Optional baseline folder to compare against.
    --fail-on-regression: Optional flag to fail on phash/MAD differences.
    --headed: Optional flag to launch the browser in headed mode.

Input Files:
    outputs/*.svg, context/staging/structural-model.json

Output:
    Exit code 0 on PASS, 1 on FAIL with comprehensive HTML/Markdown dashboards.

Key Functions:
    sheet_kind: Identifies if a sheet is a presentation drawing or fabrication blueprint.
    project_iso: Performs isometric projection coordinates calculation.
    compute_hub_crop: Estimates viewport cropping bounding box for high-density hub crops.
    evaluate_image: Checks basic image heuristics (blankness, centering, tiny cluster).
    evaluate_image_cv: Runs Canny and Hough Line transforms to audit structural topology.

Script Dependencies:
    playwright, opencv-python (cv2), numpy, pillow

Consumed by:
    design-orchestrator (Stage 5.6 Visual Smoke Test Gate)
"""

import os
import sys
import json
import math
import argparse
from pathlib import Path
from datetime import datetime, timezone
import typing
import numpy as np
import cv2
from PIL import Image

_sync_playwright = None
try:
    from playwright.sync_api import sync_playwright as _sync_playwright  # type: ignore[assignment]
except ImportError:
    pass

# --- Shared Constants ---
SHEETS_FOR_HUB_CROP: list[str] = [
    "drawing-plan-view.svg",
    "drawing-isometric-view.svg",
    "drawing-perspective-view.svg",
    "blueprint-plan.svg",
    "blueprint-isometric.svg",
]

SHEETS_FOR_INTERSECTION_CHECK: list[str] = [
    "blueprint-isometric.svg",
    "drawing-isometric-view.svg",
    "drawing-perspective-view.svg",
]

BG_EPS: int = 18

MIN_NON_BG_RATIO: dict[str, float] = {
    "blueprint": 0.020,
    "drawing":   0.015,
}

MIN_BBOX_FILL_RATIO: dict[str, float] = {
    "blueprint": 0.060,
    "drawing":   0.080,
}

TOP_LEFT_CLUSTER_MAX_X: float = 0.25
TOP_LEFT_CLUSTER_MAX_Y: float = 0.25

HUB_CROP_MIN_HALF: int = 140
HUB_CROP_MAX_HALF: int = 320
HUB_CROP_RADIUS_FACTOR: float = 0.42

HUB_EDGE_DENSITY_MAX: dict[str, float] = {
    "blueprint-isometric": 0.28,
    "drawing-isometric":   0.32,
    "drawing-perspective": 0.34,
}
HUB_EDGE_DENSITY_MIN: dict[str, float] = {
    "blueprint-isometric": 0.06,
    "drawing-isometric":   0.05,
    "drawing-perspective": 0.05,
}

HUB_JUNCTION_RATIO_MAX: dict[str, float] = {
    "blueprint-isometric": 0.014,
    "drawing-isometric":   0.018,
    "drawing-perspective": 0.020,
}
HUB_JUNCTION_RATIO_MIN: dict[str, float] = {
    "blueprint-isometric": 0.0012,
    "drawing-isometric":   0.0010,
    "drawing-perspective": 0.0010,
}

BEAM_BAND_PAD_TOP: int = 40
BEAM_BAND_HEIGHT: int = 110
MAX_ALLOWED_GAP_PX: int = 3

PHASH_FAIL: dict[str, int] = {
    "blueprint": 14,
    "drawing":   18,
}
MAD_FAIL: dict[str, float] = {
    "blueprint": 0.040,
    "drawing":   0.055,
}

# External Comment: Map a filename to sheet classification type (blueprint or drawing)
def sheet_kind(svg_path: str) -> str:
    """
    Identifies the categorization of the target sheet based on filename cues.
    
    Args:
        svg_path: Filename or path to the SVG.
        
    Returns:
        String "blueprint" if filename starts with blueprint-, otherwise "drawing".
    """
    name = os.path.basename(svg_path).lower()
    return "blueprint" if "blueprint-" in name else "drawing"

# External Comment: Generate a normalized sheet key identifier for looking up thresholds
def hub_sheet_key(svg_path: str) -> str:
    """
    Normalizes filename to match expected metric threshold keys.
    
    Args:
        svg_path: Filename or path to the SVG.
        
    Returns:
        Normalized key name string.
    """
    base = os.path.basename(svg_path).replace(".svg", "").lower()
    if "blueprint-isometric" in base:
        return "blueprint-isometric"
    if "drawing-isometric-view" in base:
        return "drawing-isometric"
    if "drawing-perspective-view" in base:
        return "drawing-perspective"
    return base

# External Comment: Translate 3D model coordinates into 2D isometric projected pixels
def project_iso(x_ft: float, y_ft: float, z_ft: float, scale: float, cx: float, cy: float) -> tuple[float, float]:
    """
    Performs parametric isometric projection calculations from 3D space to 2D pixels.
    
    Args:
        x_ft: X dimension in feet.
        y_ft: Y dimension in feet.
        z_ft: Z dimension in feet.
        scale: Scaling multiplier (pixels per foot).
        cx: Viewport horizontal center pivot.
        cy: Viewport vertical ground pivot.
        
    Returns:
        Tuple of (px_x, px_y) coordinates.
    """
    px = x_ft * scale
    py = y_ft * scale
    pz = z_ft * scale
    iso_x = cx + (px - py) * math.cos(math.radians(30))
    iso_y = cy + (px + py) * math.sin(math.radians(30)) - pz
    return iso_x, iso_y

# External Comment: Calculate central viewport crop bounding box for hub inspection
def compute_hub_crop(structure: dict[str, typing.Any], sheet_name: str) -> typing.Optional[tuple[int, int, int, int]]:
    """
    Computes a tight bounding box around the central structural hub assembly.
    
    Args:
        structure: Loaded structural design model.
        sheet_name: Target sheet filename.
        
    Returns:
        Optional tuple of (x, y, width, height) pixels, or None on error.
    """
    try:
        geom = structure["geometry"]
        coords = geom["svg_coordinates"]
        joints = geom["joints"]
        
        scale = coords.get("scale_px_per_ft") or 55.0
        cx = coords["width_px"] / 2
        
        post_h = geom["total_height"]["post_ft"]
        roof_r = geom["roof_rise"]["rise_ft"]
        
        if "perspective" in sheet_name or "isometric" in sheet_name:
            inscribed_r = structure["layout"]["inscribed_radius_ft"]
            sides = structure["layout"]["post_count"]
            span_diag = round(2 * inscribed_r / math.cos(math.pi / sides), 3)
            approx_h = post_h + roof_r + span_diag * 0.5
            available_h = coords["height_px"] - 250
            scale = min(scale, available_h / approx_h)
            cy = coords["height_px"] - 200
        else:
            cy = coords["height_px"] / 2 - 20
            
        Z_APEX = joints.get("z_planes", {}).get("Z_APEX", geom["total_height"]["total_height_ft"])
        hub_apex = [0.0, 0.0, Z_APEX]
        
        if "perspective" in sheet_name or "isometric" in sheet_name:
            p_hub = project_iso(hub_apex[0], hub_apex[1], hub_apex[2], scale, cx, cy)
        else:
            p_hub = (cx, cy)
            
        term_pts = joints.get("rafters", {}).get("hub_termination_points", {}).get("points", [])
        if not term_pts:
            return None
            
        max_r = 0.0
        for pt_item in term_pts:
            pt = pt_item["point"] if isinstance(pt_item, dict) and "point" in pt_item else pt_item
            if "perspective" in sheet_name or "isometric" in sheet_name:
                p_tip = project_iso(pt[0], pt[1], pt[2], scale, cx, cy)
            else:
                p_tip = (cx + pt[0] * 80.0, cy + pt[1] * 80.0)
            dist = math.sqrt((p_hub[0]-p_tip[0])**2 + (p_hub[1]-p_tip[1])**2)
            max_r = max(max_r, dist)
            
        crop_half = max(HUB_CROP_MIN_HALF, min(int(max_r * HUB_CROP_RADIUS_FACTOR), HUB_CROP_MAX_HALF))
        
        x_crop = int(p_hub[0] - crop_half)
        y_crop = int(p_hub[1] - crop_half)
        w_crop = int(crop_half * 2)
        h_crop = int(crop_half * 2)
        
        return (x_crop, y_crop, w_crop, h_crop)
    except Exception as e:
        print(f"Failed to compute hub crop: {e}")
        return None

# External Comment: Process raster screenshot and calculate basic layout metrics
def evaluate_image(img_path: str, kind: str) -> tuple[dict[str, typing.Any], list[str]]:
    """
    Validates simple visual heuristics like empty canvas, centering, or scale collapses.
    
    Args:
        img_path: File path of the PNG screenshot.
        kind: Classification "blueprint" or "drawing".
        
    Returns:
        Tuple of (metrics, failures).
    """
    metrics: dict[str, typing.Any] = {}
    failures: list[str] = []
    
    try:
        img = Image.open(img_path).convert("RGB")
        w, h = img.size
        metrics["viewport_px"] = [w, h]
        
        arr = np.array(img)
        corners = [arr[0,0], arr[0,-1], arr[-1,0], arr[-1,-1]]
        bg_color = np.median(corners, axis=0)
        
        diff = np.abs(arr - bg_color).sum(axis=2)
        non_bg_mask = diff > BG_EPS
        non_bg_ratio = np.sum(non_bg_mask) / (w * h)
        metrics["non_bg_ratio"] = float(non_bg_ratio)
        
        if non_bg_ratio < MIN_NON_BG_RATIO[kind]:
            failures.append("VISUAL_BLANK")
            
        if np.any(non_bg_mask):
            rows = np.any(non_bg_mask, axis=1)
            cols = np.any(non_bg_mask, axis=0)
            ymin, ymax = np.where(rows)[0][[0, -1]]
            xmin, xmax = np.where(cols)[0][[0, -1]]
            
            bbox_area = (ymax - ymin) * (xmax - xmin)
            bbox_fill_ratio = bbox_area / (w * h)
            metrics["bbox_fill_ratio"] = float(bbox_fill_ratio)
            
            if bbox_fill_ratio < MIN_BBOX_FILL_RATIO[kind]:
                failures.append("VISUAL_TINY_CLUSTER")
                
            if xmax < w * TOP_LEFT_CLUSTER_MAX_X and ymax < h * TOP_LEFT_CLUSTER_MAX_Y:
                metrics["top_left_clustered"] = True
                failures.append("VISUAL_TOP_LEFT_CLUSTER")
            else:
                metrics["top_left_clustered"] = False
        else:
            metrics["bbox_fill_ratio"] = 0.0
            metrics["top_left_clustered"] = False
            
    except Exception as e:
        failures.append(f"IMAGE_PROCESSING_ERROR: {e}")
        
    return metrics, failures

# External Comment: Process high-resolution hub crop and calculate edge density
def evaluate_hub_crop(img_path: str, sheet_key: str) -> tuple[dict[str, typing.Any], list[str]]:
    """
    Validates edge complexity inside the hub region to detect missing or corrupted joints.
    
    Args:
        img_path: File path of the cropped hub PNG.
        sheet_key: Normalized sheet key.
        
    Returns:
        Tuple of (metrics, failures).
    """
    metrics: dict[str, typing.Any] = {}
    failures: list[str] = []
    
    try:
        img = Image.open(img_path).convert("L")
        arr = np.array(img)
        
        dx = np.diff(arr, axis=1, append=arr[:, -1:])
        dy = np.diff(arr, axis=0, append=arr[-1:, :])
        mag = np.sqrt(dx**2 + dy**2)
        
        edge_mask = mag > 10
        edge_density = np.sum(edge_mask) / (arr.shape[0] * arr.shape[1])
        metrics["hub_edge_density"] = float(edge_density)
        
        max_thresh = HUB_EDGE_DENSITY_MAX.get(sheet_key) or 0.4
        min_thresh = 0.005
        
        if edge_density > max_thresh:
            failures.append("SPAGHETTI_HUB_RISK")
        elif edge_density < min_thresh:
            failures.append("HUB_CROP_EMPTY_OR_WRONG")
            
    except Exception as e:
        failures.append(f"HUB_PROCESSING_ERROR: {e}")
        
    return metrics, failures

# External Comment: Extracts expected framing member counts from structure spec model
def extract_expected_topology(structure: dict[str, typing.Any]) -> dict[str, int]:
    """
    Determines structural components quantities from specification.
    
    Args:
        structure: Design parameters model.
        
    Returns:
        Dict mapping element names (posts, beams, rafters) to integer counts.
    """
    layout = structure.get("layout", {})
    roof = structure.get("roof", {})
    hub = structure.get("hub", {})
    bracing = structure.get("bracing", {})
    
    brace_spec = bracing.get("brace", {})
    count_per_post = brace_spec.get("count_per_post")
    if count_per_post is None:
        count_per_post = 2 if bracing.get("layout") == "paired_per_post" else 1

    post_cnt = layout.get("post_count") or 0
    primary_cnt = (roof.get("primary_rafters") or {}).get("count") or 0
    return {
        "posts": post_cnt,
        "beams": post_cnt,
        "rafters": primary_cnt,
        "hub": 1 if hub.get("type") and hub.get("type") != "none" else 0,
        "braces": (post_cnt * count_per_post) if bracing.get("enabled") else 0
    }

# External Comment: Use Canny edges and Hough lines to detect posts, beams, rafters
def detect_components(image: np.ndarray) -> dict[str, int]:
    """
    Applies Canny filtering and probabilistic Hough line transforms to identify elements.
    
    Args:
        image: Multi-channel input image in BGR format.
        
    Returns:
        Dictionary mapping structural component types to estimated counts.
    """
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 50, 150)

    lines = cv2.HoughLinesP(edges, 1, np.pi/180, 50, minLineLength=50, maxLineGap=10)

    posts = beams = rafters = 0

    if lines is None:
        return {"posts": 0, "beams": 0, "rafters": 0}

    for line in lines:
        x1, y1, x2, y2 = line[0]
        dx, dy = x2 - x1, y2 - y1
        angle = abs(np.degrees(np.arctan2(dy, dx)))
        length = (dx * dx + dy * dy) ** 0.5

        if 80 < angle < 100 and length > 80:
            posts += 1
        elif angle < 10 or angle > 170:
            beams += 1
        else:
            rafters += 1

    return {
        "posts": posts // 2,
        "beams": beams // 2,
        "rafters": rafters // 2
    }

# External Comment: Measure total non-empty drawing ink density on a gray canvas
def compute_content_ratio(image: np.ndarray) -> float:
    """
    Estimates the visual coverage of structural drawings to prevent complete collapses.
    
    Args:
        image: Multi-channel input image.
        
    Returns:
        Float coverage percentage.
    """
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    return float(np.count_nonzero(gray) / (gray.shape[0] * gray.shape[1]))

# External Comment: Measures detailed edge density within a central hub cropping box
def detect_hub_density(image: np.ndarray) -> int:
    """
    Calculates count of non-zero edge pixels in a central hub window to audit complexity.
    
    Args:
        image: Standard BGR input image.
        
    Returns:
        Integer representing count of active edge pixels.
    """
    h, w = image.shape[:2]
    cx, cy = w // 2, h // 2
    crop = image[max(0, cy - 100):min(h, cy + 100), max(0, cx - 100):min(w, cx + 100)]
    gray = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 50, 150)
    return int(np.count_nonzero(edges))

# External Comment: Compares computer vision detections with expectations
def full_visual_validation(
    image: np.ndarray,
    structure: dict[str, typing.Any],
    sheet_key: str = "",
) -> list[str]:
    """
    Orchestrates full structural validations using physical expectation counts.

    Args:
        image: Standard BGR input image.
        structure: Loaded model specification JSON dict.
        sheet_key: Normalized sheet key for threshold lookup.

    Returns:
        List of failure codes. Empty list implies perfect validation.
    """
    expected = extract_expected_topology(structure)
    detected = detect_components(image)

    failures: list[str] = []

    content_ratio = compute_content_ratio(image)
    if content_ratio < 0.15:
        failures.append("LAYOUT_COLLAPSE")

    for k in expected:
        if k in ("posts", "beams", "rafters"):
            if k in detected:
                if expected[k] > 0 and detected[k] < expected[k] // 2:
                    failures.append(f"COUNT_MISMATCH_{k.upper()}")

    hub_result = detect_spaghetti_hub(detect_hub_density(image), sheet_key)
    if hub_result:
        failures.append(f"{hub_result['code']}: {hub_result['detail']}")

    brace_result = detect_brace_float(structure)
    if brace_result:
        failures.append(f"{brace_result['code']}: {brace_result['detail']}")

    beam_result = detect_beam_gap(structure)
    if beam_result:
        failures.append(f"{beam_result['code']}: {beam_result['detail']}")

    return failures

# External Comment: Evaluates image using computer vision and returns a report
def evaluate_image_cv(
    img_path: str,
    structure: dict[str, typing.Any],
    sheet_key: str = "",
) -> tuple[dict[str, typing.Any], list[str]]:
    """
    Main cv-evaluation script wrapper that reads path and runs topology heuristics.

    Args:
        img_path: Path to PNG screenshot.
        structure: Loaded structure parameters.
        sheet_key: Normalized sheet key for named-detector threshold lookup.

    Returns:
        Tuple of (cv_metrics, failures).
    """
    metrics: dict[str, typing.Any] = {}
    failures: list[str] = []
    try:
        image = cv2.imread(img_path)
        if image is None:
            return {}, ["IMAGE_LOAD_FAILED"]

        expected = extract_expected_topology(structure)
        detected = detect_components(image)
        content_ratio = compute_content_ratio(image)
        hub_density = detect_hub_density(image)

        metrics["expected_topology"] = expected
        metrics["detected_components"] = detected
        metrics["cv_content_ratio"] = float(content_ratio)
        metrics["cv_hub_density"] = int(hub_density)

        failures = full_visual_validation(image, structure, sheet_key=sheet_key)
    except Exception as e:
        failures.append(f"CV_VALIDATION_ERROR: {str(e)}")
    return metrics, failures

# External Comment: Calculate Discrete Cosine Transform (DCT) based perceptual hash
def compute_phash(img_path: str) -> typing.Optional[int]:
    """
    Computes a 64-bit DCT-based perceptual hash of an image for structural comparison.
    
    Args:
        img_path: Path to the image file.
        
    Returns:
        64-bit integer hash, or None on error.
    """
    try:
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            return None
        resized = cv2.resize(img, (32, 32), interpolation=cv2.INTER_AREA)
        dct = cv2.dct(np.float32(resized))
        dct_8x8 = dct[0:8, 0:8]
        avg = np.mean(dct_8x8)
        hash_bits = (dct_8x8 > avg).flatten()
        h = 0
        for bit in hash_bits:
            h = (h << 1) | int(bit)
        return h
    except Exception as e:
        print(f"Failed to compute pHash: {e}")
        return None

# External Comment: Calculate bitwise Hamming distance between hashes
def hamming_distance(h1: int, h2: int) -> int:
    """
    Computes Hamming distance between two 64-bit integer perceptual hashes.
    
    Args:
        h1: First perceptual hash.
        h2: Second perceptual hash.
        
    Returns:
        Integer Hamming distance representing structural differences.
    """
    return bin(h1 ^ h2).count('1')

# External Comment: Compute normalized Mean Absolute Difference (MAD) between two images
def compute_mad(img_path1: str, img_path2: str) -> tuple[float, typing.Optional[str]]:
    """
    Calculates Mean Absolute Difference (MAD) between two images normalized to [0, 1].
    
    Args:
        img_path1: Path to the first image.
        img_path2: Path to the second image.
        
    Returns:
        Tuple of (mad_score, error_message).
    """
    try:
        img1 = cv2.imread(img_path1)
        img2 = cv2.imread(img_path2)
        if img1 is None or img2 is None:
            return 1.0, "IMAGE_LOAD_FAILED"
        if img1.shape != img2.shape:
            img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]), interpolation=cv2.INTER_AREA)
        diff = np.abs(img1.astype(np.float32) - img2.astype(np.float32))
        mad = np.mean(diff) / 255.0
        return float(mad), None
    except Exception as e:
        return 1.0, f"MAD_COMPUTATION_ERROR: {e}"

# ---------------------------------------------------------------------------
# Named visual failure detectors — each returns a structured failure dict
# or None (no failure).  These replace anonymous threshold checks so that
# failure origins are unambiguous and reports are self-describing.
# ---------------------------------------------------------------------------

def detect_spaghetti_hub(hub_density: int, sheet_key: str) -> typing.Optional[dict[str, str]]:
    """
    Returns a structured failure dict if hub edge density exceeds the spaghetti threshold.
    Hub density > 5000 indicates interpenetrating members at the apex (no Boolean trimming).
    """
    threshold = 5000
    if hub_density > threshold:
        return {
            "code": "SPAGHETTI_HUB",
            "severity": "FAIL",
            "detail": (
                f"hub edge pixel count {hub_density} exceeds threshold {threshold} "
                f"on {sheet_key or 'unknown-sheet'} — secondary framing likely visible in 3D view"
            ),
        }
    return None




def detect_brace_float(structure: dict[str, typing.Any]) -> typing.Optional[dict[str, str]]:
    """
    Returns a structured failure dict if brace geometry parameters are degenerate.
    Checks resolved brace endpoints rather than raw input parameters.
    """
    bracing = structure.get("bracing", {})
    if not bracing.get("enabled"):
        return None
    joints = structure.get("geometry", {}).get("joints", {})
    braces = joints.get("braces", {})
    if not braces:
        return None
    endpoints = braces.get("endpoints", [])
    if not endpoints:
        return {
            "code": "BRACE_FLOAT",
            "severity": "FAIL",
            "detail": "bracing is enabled but geometry.joints.braces.endpoints is empty",
        }
    for brace in endpoints:
        p0 = brace["start"]
        p1 = brace["end"]
        dx = p1[0] - p0[0]
        dy = p1[1] - p0[1]
        dz = p1[2] - p0[2]
        length_in = math.sqrt(dx*dx + dy*dy + dz*dz) * 12.0
        run = math.sqrt(dx*dx + dy*dy)
        if run < 1e-6:
            angle = 90.0
        else:
            angle = math.degrees(math.atan2(abs(dz), run))
        if length_in <= 1e-3:
            return {
                "code": "BRACE_FLOAT",
                "severity": "FAIL",
                "detail": f"brace {brace['id']} length={length_in:.3f} in — zero-length brace cannot contact post face",
            }
        if not (5.0 <= angle <= 85.0):
            return {
                "code": "BRACE_FLOAT",
                "severity": "FAIL",
                "detail": f"brace {brace['id']} angle_deg={angle:.2f} is outside [5°, 85°]",
            }
    return None


def detect_beam_gap(structure: dict[str, typing.Any]) -> typing.Optional[dict[str, str]]:
    """
    Returns a structured failure dict if beam_span_ft is missing or deviates
    significantly from the expected post-to-post chord length.
    A gap means the beam doesn't connect to the posts it's supposed to span.
    """
    geom = structure.get("geometry", {})
    spans = geom.get("spans", {})
    if "beam_span_ft" not in spans:
        return None  # geometry_engine hasn't populated spans yet — skip rather than false-fail
    beam_span = float(spans["beam_span_ft"])
    if beam_span <= 0:
        return {
            "code": "BEAM_GAP",
            "severity": "FAIL",
            "detail": f"beam_span_ft={beam_span} — zero beam span in geometry.spans",
        }
    inscribed = float(structure.get("layout", {}).get("inscribed_radius_ft") or 0.0)
    qty = int(structure.get("layout", {}).get("post_count") or 0)
    if inscribed > 0 and qty > 2:
        expected_span = 2.0 * inscribed * math.sin(math.pi / qty)
        delta = abs(beam_span - expected_span)
        if delta > 0.5:
            return {
                "code": "BEAM_GAP",
                "severity": "WARN",
                "detail": (
                    f"beam_span_ft={beam_span:.3f} differs from post chord {expected_span:.3f} ft "
                    f"by {delta:.3f} ft — beam endpoints may not align with posts"
                ),
            }
    return None


# External Comment: Parse CLI parameters, spawn Playwright web instance, run smoke checks
from path_utils import staging_dir, outputs_dir

def main() -> None:
    """
    Command line interface entry point orchestrating screenshots and visual assertions.
    """
    _STAGING = staging_dir()
    _OUTPUTS = outputs_dir()
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--structure", default=str(_STAGING / "structure.json"))
    parser.add_argument("--svg-dir", default=str(_OUTPUTS))
    parser.add_argument("--out-dir", default=str(_OUTPUTS / "visual-smoke"))
    parser.add_argument("--report-json", default=str(_STAGING / "visual-smoke-report.json"))
    parser.add_argument("--report-md", default=str(_OUTPUTS / "visual-smoke-report.md"))
    parser.add_argument("--baseline-dir")
    parser.add_argument("--fail-on-regression", action="store_true")
    parser.add_argument("--headed", action="store_true", help="Run browser in headed mode for visual debugging")
    args = parser.parse_args()

    Path(args.out_dir).mkdir(parents=True, exist_ok=True)
    Path(args.report_json).parent.mkdir(parents=True, exist_ok=True)
    Path(args.report_md).parent.mkdir(parents=True, exist_ok=True)

    with open(args.structure) as f:
        structure = json.load(f)

    if not bool(structure.get("geometry", {}).get("_sealed")):
        print("GEOMETRY_NOT_SEALED: Cannot run visual tests on unsealed geometry.")
        sys.exit(1)

    all_sheets: list[str] = [
        "drawing-plan-view.svg",
        "drawing-elevation-view.svg",
        "drawing-isometric-view.svg",
        "drawing-perspective-view.svg",
        "blueprint-plan.svg",
        "blueprint-elevation.svg",
        "blueprint-isometric.svg",
        "blueprint-component-isolation.svg",
    ]

    report: dict[str, typing.Any] = {
        "schema": "garden-structure-designer/visual-smoke-report/1.0",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "source_hash": structure.get("meta", {}).get("source_hash", "unknown"),
        "structure_path": args.structure,
        "svg_dir": args.svg_dir,
        "out_dir": args.out_dir,
        "baseline_dir": args.baseline_dir,
        "status": "PASS",
        "summary": "All sheets rendered and heuristics passed.",
        "files": [],
        "overall_failures": [],
        "overall_warnings": [],
        "may_claim_success": True
    }

    overall_failures: list[str] = []
    width = structure["geometry"]["svg_coordinates"]["width_px"]
    height = structure["geometry"]["svg_coordinates"]["height_px"]

    try:
        for sheet in all_sheets:
            sheet_path = Path(args.svg_dir) / sheet
            if not sheet_path.exists():
                overall_failures.append(f"SVG_MISSING: {sheet}")
                continue

            kind = sheet_kind(sheet)
            png_name = sheet.replace(".svg", ".png")
            png_path = Path(args.out_dir) / png_name
            
            file_report: dict[str, typing.Any] = {
                "sheet": sheet.replace(".svg", ""),
                "svg": str(sheet_path),
                "png": str(png_path),
                "metrics": {},
                "failures": [],
                "warnings": []
            }

            # Staleness gate: PNG must not be older than its source SVG.
            # A stale PNG means the SVG was regenerated but the PNG wasn't — delete
            # it here so the qlmanage fallback below produces fresh evidence.
            if png_path.exists() and png_path.stat().st_size > 0:
                if png_path.stat().st_mtime < sheet_path.stat().st_mtime:
                    print(f"[SMOKE] PNG_STALE_OR_MISSING: {sheet} — PNG older than SVG, re-rendering")
                    file_report["warnings"].append(
                        f"PNG_STALE_OR_MISSING: PNG was older than SVG for {sheet} — re-rendered"
                    )
                    png_path.unlink()

            # PNGs are pre-generated by render_drawings.py alongside SVG output.
            # Only fall back to qlmanage (or Playwright) when the PNG is absent.
            if not png_path.exists() or png_path.stat().st_size == 0:
                import subprocess
                print(f"[SMOKE] PNG not pre-generated — falling back to qlmanage: {sheet}")
                subprocess.run(
                    ["qlmanage", "-t", "-s", str(width), "-o", str(args.out_dir), str(sheet_path)],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
                ql_out = Path(args.out_dir) / (sheet + ".png")
                if ql_out.exists():
                    if png_path.exists():
                        png_path.unlink()
                    ql_out.rename(png_path)

            # Last-resort: Playwright (if installed and PNG still missing)
            if (not png_path.exists() or png_path.stat().st_size == 0) and _sync_playwright is not None:
                print(f"[SMOKE] qlmanage failed — falling back to Playwright: {sheet}")
                try:
                    with _sync_playwright() as p:
                        browser = p.chromium.launch()
                        page = browser.new_page(viewport={"width": width, "height": height})
                        page.goto(sheet_path.resolve().as_uri())
                        page.screenshot(path=str(png_path), full_page=False)
                        browser.close()
                except Exception as _pw_err:
                    print(f"[SMOKE] Playwright fallback failed: {_pw_err}", file=sys.stderr)

            if not png_path.exists() or png_path.stat().st_size == 0:
                print(f"[SMOKE] PNG rendering failed for {sheet}")
                file_report["failures"].append("BROWSER_RENDER_BLOCKED")
                overall_failures.append(f"BROWSER_RENDER_BLOCKED: {sheet}")
                report["files"].append(file_report)
                continue

            metrics, failures = evaluate_image(str(png_path), kind)
            file_report["metrics"].update(metrics)
            file_report["failures"].extend(failures)

            cv_metrics, cv_failures = evaluate_image_cv(str(png_path), structure, sheet_key=hub_sheet_key(sheet))
            file_report["metrics"].update(cv_metrics)
            if "isolation" not in sheet:
                file_report["failures"].extend(cv_failures)

            # Perceptual hash & Mean Absolute Difference (MAD) baseline validation
            if args.baseline_dir:
                base_png = Path(args.baseline_dir) / png_name
                if base_png.exists():
                    mad, err = compute_mad(str(png_path), str(base_png))
                    ph1 = compute_phash(str(png_path))
                    ph2 = compute_phash(str(base_png))
                    dist = hamming_distance(ph1, ph2) if (ph1 is not None and ph2 is not None) else 0

                    file_report["metrics"]["baseline_mad"] = mad
                    file_report["metrics"]["baseline_phash_distance"] = dist

                    if args.fail_on_regression:
                        if err:
                            file_report["failures"].append(f"BASELINE_COMPARISON_ERROR: {err}")
                        elif dist > PHASH_FAIL[kind]:
                            file_report["failures"].append("VISUAL_REGRESSION_PHASH_DISTORTION")
                        elif mad > MAD_FAIL[kind]:
                            file_report["failures"].append("VISUAL_REGRESSION_MAD_DRIFT")

            if sheet in SHEETS_FOR_HUB_CROP:
                clip_raw = compute_hub_crop(structure, sheet)
                if clip_raw:
                    cx, cy, cw, ch = clip_raw
                    clamped_x = max(0, cx)
                    clamped_y = max(0, cy)
                    clamped_w = min(cw, width - clamped_x)
                    clamped_h = min(ch, height - clamped_y)
                    
                    hub_png_name = sheet.replace(".svg", ".hub.png")
                    hub_png_path = Path(args.out_dir) / hub_png_name
                    
                    # Generate hub crop via Pillow if missing or empty
                    if not hub_png_path.exists() or hub_png_path.stat().st_size == 0:
                        try:
                            with Image.open(str(png_path)) as img:
                                cropped_img = img.crop((clamped_x, clamped_y, clamped_x + clamped_w, clamped_y + clamped_h))
                                cropped_img.save(str(hub_png_path))
                        except Exception as err:
                            print(f"[SMOKE] Crop failed for {sheet}: {err}")
                            file_report["failures"].append("BROWSER_RENDER_BLOCKED")
                            overall_failures.append(f"BROWSER_RENDER_BLOCKED (Hub Crop): {sheet}")
                            report["files"].append(file_report)
                            continue

                    if not hub_png_path.exists() or hub_png_path.stat().st_size == 0:
                        file_report["failures"].append("BROWSER_RENDER_BLOCKED")
                        overall_failures.append(f"BROWSER_RENDER_BLOCKED (Hub Crop): {sheet}")
                        report["files"].append(file_report)
                        continue
                    
                    file_report["hub_crop_png"] = str(hub_png_path)
                    file_report["clip"] = {"hub_box_px": [cx, cy, cw, ch]}
                    
                    h_metrics, h_failures = evaluate_hub_crop(str(hub_png_path), hub_sheet_key(sheet))
                    file_report["metrics"].update(h_metrics)
                    file_report["failures"].extend(h_failures)
                else:
                    file_report["warnings"].append("Could not compute hub crop window.")

            file_report["status"] = "FAIL" if file_report["failures"] else "PASS"
            report["files"].append(file_report)
    except Exception as outer_err:
        print(f"[SMOKE] Visual smoke test critical error: {outer_err}", file=sys.stderr)
        sys.exit(1)

    has_fails = len(overall_failures) > 0 or any(f["status"] == "FAIL" for f in report["files"])
    
    if has_fails:
        report["status"] = "FAIL"
        report["may_claim_success"] = False
        report["summary"] = "Visual smoke test failed heuristics."
        
    report["overall_failures"] = overall_failures
    
    with open(args.report_json, "w") as f:
        json.dump(report, f, indent=2)

    md = [
        "# Visual Smoke Test Report (SVG -> Browser Render)",
        "",
        f"**Schema:** {report['schema']}  ",
        f"**Generated:** {report['generated_at']}  ",
        f"**Source Hash:** `{report['source_hash']}`  ",
        f"**Structure:** `{report['structure_path']}`  ",
        f"**SVG Dir:** `{report['svg_dir']}`  ",
        f"**Out Dir:** `{report['out_dir']}`  ",
        f"**Baseline Dir:** `{report['baseline_dir']}`  ",
        f"**Mode:** {'fail-on-regression' if args.fail_on_regression else 'no-baseline'}  ",
        "",
        "**Run Command:**",
        f"`python3 plugins/garden-structure-designer/scripts/visual_svg_smoke_test.py --structure {args.structure} --svg-dir {args.svg_dir}`",
        "",
        "---",
        "",
        f"## STATUS: **{report['status']}**",
        f"**may_claim_success:** `{report['may_claim_success']}`",
        "",
        "### Summary",
        f"{report['summary']}",
        "",
        "---",
        "",
        "## Overall Failures"
    ]
    
    if not report["overall_failures"]:
        md.append("- *(none)*")
    else:
        for f in report["overall_failures"]:
            md.append(f"- {f}")
            
    md.append("")
    md.append("## Overall Warnings")
    if not report["overall_warnings"]:
        md.append("- *(none)*")
    else:
        for w in report["overall_warnings"]:
            md.append(f"- {w}")
            
    md.append("")
    md.append("---")
    md.append("")
    md.append("# Per-Sheet Results")
    
    for fr in report["files"]:
        md.append(f"### {fr['sheet']}")
        md.append(f"**Status:** **{fr['status']}**  ")
        md.append(f"**SVG:** `{fr['svg']}`  ")
        md.append(f"**PNG:** `{fr['png']}`  ")
        
        if "hub_crop_png" in fr:
            md.append(f"**Hub Crop PNG:** `{fr['hub_crop_png']}`  ")
            md.append(f"**Hub Clip (px):** `{fr['clip'].get('hub_box_px')}`  ")
            
        md.append("")
        md.append("#### Metrics")
        md.append(f"- non_bg_ratio: `{fr['metrics'].get('non_bg_ratio') or 0.0:.4f}`")
        md.append(f"- bbox_fill_ratio: `{fr['metrics'].get('bbox_fill_ratio') or 0.0:.4f}`")
        md.append(f"- top_left_clustered: `{bool(fr['metrics'].get('top_left_clustered'))}`")
        
        if "cv_content_ratio" in fr["metrics"]:
            md.append(f"- cv_content_ratio: `{fr['metrics']['cv_content_ratio']:.4f}`")
        if "cv_hub_density" in fr["metrics"]:
            md.append(f"- cv_hub_density: `{fr['metrics']['cv_hub_density']}`")
        if "expected_topology" in fr["metrics"]:
            md.append(f"- expected_topology: `{fr['metrics']['expected_topology']}`")
        if "detected_components" in fr["metrics"]:
            md.append(f"- detected_components: `{fr['metrics']['detected_components']}`")
            
        if "hub_edge_density" in fr["metrics"]:
            md.append(f"- hub_edge_density: `{fr['metrics']['hub_edge_density']:.4f}`")
            
        md.append("")
        md.append("#### Failures")
        if not fr["failures"]:
            md.append("- *(none)*")
        else:
            for f in fr["failures"]:
                md.append(f"- {f}")
        
        md.append("")
        md.append("#### Warnings")
        if not fr["warnings"]:
            md.append("- *(none)*")
        else:
            for w in fr["warnings"]:
                md.append(f"- {w}")
        
        md.append("")
        md.append("---")

    md.extend([
        "",
        "## Artifacts Produced",
        f"- JSON report: `{args.report_json}`",
        f"- This report: `outputs/visual-smoke-report.md`",
        f"- Screenshots: `{args.out_dir}/<sheet>.png`",
        ""
    ])

    with open(args.report_md, "w") as f:
        f.write("\n".join(md))

    if not report["may_claim_success"]:
        sys.exit(1)

if __name__ == "__main__":
    main()
